<?php

namespace App\Services\Content;

use App\Enums\Database\ContentType;
use App\Models\Content;
use App\Repositories\Content\ContentRepositoryInterface;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Spatie\QueryBuilder\AllowedFilter;

/**
 * Service class for Content business logic
 */
class ContentService
{
    /**
     * @param ContentRepositoryInterface $repository
     */
    public function __construct(
        private readonly ContentRepositoryInterface $repository
    ) {
    }

    /**
     * Get all contents with optional filters using QueryBuilder.
     *
     * @param int $perPage
     * @return LengthAwarePaginator
     */
    public function search(int $perPage = 15): LengthAwarePaginator
    {
        $allowedFilters = [
            AllowedFilter::partial('title'),
            AllowedFilter::partial('slug'),
            AllowedFilter::exact('type'),
            AllowedFilter::exact('is_active'),
            AllowedFilter::callback('search', function ($query, $value) {
                $query->where(function ($q) use ($value) {
                    $q->where('title', 'like', "%{$value}%")
                        ->orWhere('slug', 'like', "%{$value}%")
                        ->orWhere('body', 'like', "%{$value}%");
                });
            }),
        ];

        $allowedSorts = [
            'id',
            'title',
            'slug',
            'type',
            'is_active',
            'visit_count',
            'created_at',
            'updated_at',
        ];

        $defaultSort = '-created_at';

        return $this->repository->search($allowedFilters, $allowedSorts, $defaultSort, $perPage);
    }

    /**
     * Find content by ID.
     *
     * @param int|string $id
     * @return Content
     * @throws ModelNotFoundException
     */
    public function findById(int|string $id): Content
    {
        return $this->repository->findByIdOrFail($id);
    }

    /**
     * Create a new content.
     *
     * @param array $data
     * @return Content
     */
    public function create(array $data): Content
    {
        // Remove slug if provided (auto-generated by trait)
        unset($data['slug']);

        // Remove is_undeletable if provided (handled by seeder/database only)
        unset($data['is_undeletable']);

        // Handle boolean fields
        if (isset($data['is_active']) && is_bool($data['is_active'])) {
            $data['is_active'] = $data['is_active'] ? 1 : 0;
        }

        // Set default visit count
        $data['visit_count'] = $data['visit_count'] ?? 0;

        return $this->repository->create($data);
    }

    /**
     * Update an existing content.
     *
     * @param int|string $id
     * @param array $data
     * @return Content
     */
    public function update(int|string $id, array $data): Content
    {
        // Remove slug if provided (auto-generated by trait)
        unset($data['slug']);

        // Remove is_undeletable if provided (handled by seeder/database only)
        unset($data['is_undeletable']);

        // Handle boolean fields
        if (isset($data['is_active']) && is_bool($data['is_active'])) {
            $data['is_active'] = $data['is_active'] ? 1 : 0;
        }

        return $this->repository->update($id, $data);
    }

    /**
     * Delete a content.
     *
     * @param int|string $id
     * @return bool
     */
    public function delete(int|string $id): bool
    {
        $content = $this->repository->findByIdOrFail($id);

        // Check if content is undeletable
        if ($content->is_undeletable) {
            throw new \RuntimeException('This content cannot be deleted.');
        }

        return $this->repository->delete($id);
    }

    /**
     * Get active content by type.
     *
     * @param ContentType $type
     * @param int|null $limit
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getActiveContentByType(ContentType $type, ?int $limit = null): \Illuminate\Database\Eloquent\Collection
    {
        $query = Content::where('type', $type)
            ->where('is_active', true)
            ->orderBy('created_at', 'desc');

        if ($limit !== null) {
            $query->limit($limit);
        }

        return $query->get();
    }

    /**
     * Get active content by type and slug.
     *
     * @param ContentType $type
     * @param string $slug
     * @return Content|null
     */
    public function getActiveContentByTypeAndSlug(ContentType $type, string $slug): ?Content
    {
        $content = $this->repository->findActiveByTypeAndSlug($type, $slug);

        if ($content) {
            // Increment visit count
            $content->incrementVisitCount();
        }

        return $content;
    }
}

