<?php

namespace Database\Factories;

use App\Enums\Database\ProductStatus;
use App\Enums\Database\ProductUnit;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Product::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->words(3, true),
            // Slug will be auto-generated by HasPersianSlug trait
            'sale_description' => fake()->optional(70)->sentence(10),
            'unit' => fake()->randomElement(ProductUnit::cases()),
            'category_id' => null,
            'is_published' => fake()->boolean(80),
            'body' => fake()->optional(80)->paragraphs(3, true),
            'price_label' => fake()->optional(50)->words(2, true),
            'meta_title' => fake()->optional(60)->sentence(5),
            'meta_description' => fake()->optional(50)->sentence(10),
            'meta_keywords' => fake()->optional(40)->words(5, true),
            'status' => fake()->randomElement(ProductStatus::cases()),
            'sort_order' => fake()->numberBetween(0, 100),
            'current_price' => fake()->optional(70)->randomFloat(0, 100000, 100000000),
            'currency_code' => fake()->optional(70)->randomElement(['IRR', 'USD', 'EUR']),
            'price_updated_at' => fake()->optional(60)->dateTimeBetween('-30 days', 'now'),
            'price_effective_date' => fake()->optional(50)->dateTimeBetween('now', '+60 days'),
        ];
    }

    /**
     * Indicate that the product is active.
     *
     * @return static
     */
    public function active(): static
    {
        return $this->state(fn(array $attributes) => [
            'status' => ProductStatus::ACTIVE,
            'is_published' => true,
        ]);
    }

    /**
     * Indicate that the product is published.
     *
     * @return static
     */
    public function published(): static
    {
        return $this->state(fn(array $attributes) => [
            'is_published' => true,
        ]);
    }
}
